# Generated by Django 4.0.4 on 2022-04-14 06:05

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField()),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FF0000", image_field=None, max_length=18, samples=None),
                ),
                (
                    "parent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.category"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Priority",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField()),
                (
                    "color",
                    colorfield.fields.ColorField(default="#FF0000", image_field=None, max_length=18, samples=None),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField()),
                ("source", models.CharField(max_length=200)),
                ("spent_at", models.DateTimeField()),
                ("notes", models.CharField(blank=True, max_length=1000, null=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="expenses.category")),
                (
                    "parent",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.expense"),
                ),
                (
                    "priority",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.priority"),
                ),
            ],
        ),
    ]
