# Generated by Django 4.0.4 on 2022-04-15 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_category_created_at_category_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="priority",
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.category"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="expenses.expense"
            ),
        ),
        migrations.DeleteModel(
            name="Priority",
        ),
    ]
