# Generated by Django 4.0.4 on 2022-04-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_remove_category_priority_remove_expense_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="public_id",
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="public_id",
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="expenses.category",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="expenses.category"
            ),
        ),
    ]
