# Generated by Django 4.0.4 on 2022-04-16 21:45

from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_category_public_id_expense_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='public_id',
            field=models.CharField(default=expenses.models.generate_public_id, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='public_id',
            field=models.CharField(default=expenses.models.generate_public_id, editable=False, max_length=50, unique=True),
        ),
    ]
