name: CI

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        command:
          - black
          - isort
          - pylint
          - mypy
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.3
          cache: 'pipenv'
          cache-dependency-path: |
            backend/Pipfile.lock
      - name: Install Python dependencies
        run: |
          pip install --user pipenv
          pipenv sync --dev
        working-directory: backend
      - name: Run linting
        run: |
          set -o allexport
          source .envs/test.env
          set +o allexport
          pipenv run python manage.py lint ${{ matrix.command }}
        working-directory: backend
