name: CI

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.3
          cache: 'pipenv'
          cache-dependency-path: |
            backend/Pipfile.lock
      - name: Install Python dependencies
        run: |
          cd backend
          pip install --user pipenv
          pipenv sync --dev --system
      - name: black
        id: black
        run: |
          black --check --diff $(git ls-files '*.py')
        continue-on-error: true
      - name: isort
        id: isort
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: |
            isort --diff $(git ls-files '*.py')
        continue-on-error: true
      - name: pylint
        id: pylint
        run: |
          pylint $(git ls-files '*.py')
        continue-on-error: true
      - name: mypy
        id: mypy
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: mypy
          run: |
            mypy $(git ls-files '*.py')
        continue-on-error: true
      - name: Check on failures
        if: steps.hello.outputs.status == 'failure' || steps.world.outputs.status == 'failure'
        run: exit 1
