name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.3
          cache: 'pipenv'
          cache-dependency-path: |
            backend/Pipfile.lock
      - name: Install Python dependencies
        run: |
          cd backend
          pip install --user pipenv
          pipenv sync
      - name: Run black/isort
        run: |
          cd backend
          pipenv run black . --check --diff
          pipenv run isort --diff -rc .
      - name: Run pylint
        run: |
          cd backend
          pipenv run pylint .
      - name: Run mypy
        run: |
          cd backend
          pipenv run mypy .
