name: 'Tests'
on:
  push:
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Run linters
      uses: sunnysid3up/python-linter@master
      with:
        django: true
        source: "./backend"
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: "echo TODO: run tests"
